task: llm-sft
base_model: meta-llama/Llama-3.2-1B
project_name: llama3-autotrain
log: tensorboard
backend: local

data:
  path: OLAIR/Open-R1-Ko-SFT-v2.0
  train_split: train
  valid_split: null
  chat_template: tokenizer
  column_mapping:
    text_column: messages

params:
  block_size: 2048
  model_max_length: 4096
  epochs: 1
  batch_size: 10
  lr: 1e-5
  peft: true
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: paged_adamw_8bit
  scheduler: linear
  gradient_accumulation: 8
  mixed_precision: bf16
  merge_adapter: true
