task: llm-dpo
base_model: meta-llama/Llama-3.2-1B
project_name: llama3-autotrain
log: tensorboard
backend: local

data:
  path: mlabonne/orpo-dpo-mix-40k
  train_split: train
  valid_split: null
  chat_template: chatml
  column_mapping:
    text_column: chosen
    rejected_text_column: rejected
    prompt_text_column: prompt

params:
  block_size: 1024
  model_max_length: 2048
  max_prompt_length: 512
  epochs: 1
  batch_size: 10
  lr: 3e-5
  peft: true
  quantization: int4
  target_modules: all-linear
  padding: right
  optimizer: adamw_torch
  scheduler: linear
  gradient_accumulation: 4
  mixed_precision: bf16
  merge_adapter: true
